### ISSUE TITLE
Fade effect

### ISSUE THREAD

**Issue by entelzonta** [donnersm/14ChannelAnalyzerV2.0#1]
Hi,

How can i fade effect like as platinium did

**Comment by donnersm** [comment]
Well, you can use his software :-). 
What do you mean by fading, can you be more specific.
I am working on a version that shows color gradient on each bar, is that what you mean?

**Comment by entelzonta** [comment]
Hi again, i made your pcb :) 

I mean always soft changing color random like YouTube link in video

https://youtu.be/xDKbpwumgF8 start from 4.00 

have a nice day

**Comment by donnersm** [comment]
Yes, I think I understand what you mean..
AS a fact...I already implemented it in the next release but I am not ready to share it this time.
AS soon as I perfect it, maybe within a week or two, I will publish it here on github.
In my latest video, you can see all the available new modes ..check it out here at timestamp 14:52
https://youtu.be/PdaYj1fz3k4?t=892

**Comment by entelzonta** [comment]
Thank you, I'm so excited, I'm looking forward to the new release

**Comment by donnersm** [comment]
New software with the implemtation as mentioned above has been released some time ago. Closing this Issue
